name: Lint

on:
  push:
    branches: [ "main-*.*.*", "dev-*.*.*", "main-*.*", "dev-*.*"]
  pull_request:
    branches: [ "main-*.*.*", "dev-*.*.*", "main-*.*", "dev-*.*"]
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup environment
        run: 
          (curl -LsSf https://astral.sh/uv/install.sh | sh) && 
          uv tool install beet --with mecha

      - name: lint datapack
        run:
          beet build
