name: Lint

on:
  push:
    branches: [ "main-*.*.*", "dev-*.*.*", "main-*.*", "dev-*.*"]
  pull_request:
    branches: [ "main-*.*.*", "dev-*.*.*", "main-*.*", "dev-*.*"]
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: datapack-linter
        uses: mcbeet/check-commands@v1.1.1
        with:
          source: .
          stats: true
          minecraft: 1.20.5

