name: Archive and release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  lint:
    uses: ./.github/workflows/lint.yaml

  build-and-release:
    needs: lint
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine Minecraft Version
        id: mc_version
        shell: bash
        run: |
          BRANCH_NAME=$(git branch -r --contains ${{ github.ref_name }} | grep -E 'origin/(mc/|main-)' | head -n 1 | sed 's|[[:space:]]*origin/||')
          
          if [ -z "$BRANCH_NAME" ]; then
            BRANCH_NAME="${{ github.ref_name }}"
          fi
          
          MC_VER=$(echo "$BRANCH_NAME" | sed -E 's|(mc/|main-)||')
          
          if [ -z "$MC_VER" ]; then
            MC_VER="unknown"
          fi
          
          echo "version=${MC_VER}" >> $GITHUB_OUTPUT
          echo "Archive name will contain Minecraft version: ${MC_VER}"

      - name: Update pack.mcmeta version
        env:
          RELEASE_VERSION: "${{ github.ref_name }}"
        run: |
          if [ -f "./pack.mcmeta" ]; then
            jq --arg ver "\n\u00A77Version $RELEASE_VERSION" '.pack.description |= . + $ver' ./pack.mcmeta > ./pack.mcmeta.tmp && mv ./pack.mcmeta.tmp ./pack.mcmeta
          fi

      - name: Archive files
        id: archive
        run: |
          FILE_NAME="VeinMiner-${{ github.ref_name }}-mc${{ steps.mc_version.outputs.version }}.zip"
          
          mkdir -p dist
          zip -rq "./dist/${FILE_NAME}" ./data/ ./pack.mcmeta ./pack.png
          
          echo "filename=${FILE_NAME}" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }} (MC ${{ steps.mc_version.outputs.version }})"
          generateReleaseNotes: true
          artifacts: "./dist/${{ steps.archive.outputs.filename }}"
          artifactContentType: "application/zip"
          artifactErrorsFailBuild: true
          makeLatest: true
